/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io;

public class App {
    public static void main(String[] args) {
        System.out.println("Main method!");
    }
}
